markdown: rdiscount
highlighter: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Yongjian Xu
subTitle: 徐永健的个人博客
description:
url: 
feed: /atom.xml

#文章分类
classification:
    - name: Git
    - name: C
    - name: C++
    - name: Linux
    - name: Shell
    - name: Vim
    - name: Algorithm

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: Archives
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: Useful links
    url: /links.html
    icon: icon-bookmark
    class: none
  - text: About me
    url: /contact.html
    icon: icon-envelope-alt
    class: none

page:
  - text: Archives
    url: /archives.html
    last: true
  - text: Useful Links
    url: /links.html
    last: true
  - text: About Me
    url: /contact.html
    last: false

author:
  name: Yongjian Xu
  email: xuyongjiande@gmail.com
